from datetime import time

# Engagement
ENGAGEMENT_COOLDOWN_SECONDS = 15
ENGAGEMENT_SAVE_INTERVAL_SECONDS = 60
XP_PER_MESSAGE_MIN = 8
XP_PER_MESSAGE_MAX = 8
XP_GM_BONUS = 50

# GM
GM_RESET_TIME = time(5, 30)
GM_SAVE_INTERVAL_SECONDS = 60

# Analytics
ANALYTICS_SAVE_INTERVAL_MINUTES = 5
ANALYTICS_ARCHIVE_BUFFER_SIZE = 100
ANALYTICS_MESSAGE_CACHE_SIZE = 20
ANALYTICS_MESSAGE_CACHE_TTL_SECONDS = 600
ANALYTICS_WORD_COUNT_TOP_N = 50
ANALYTICS_DEBUG_WORDS = False
